export const BACKEND_STATUS_CHANGED = 'BACKEND_STATUS_CHANGED'
export const BACKEND_MESSAGE_RECEIVED = 'BACKEND_MESSAGE_RECEIVED'
export const BACKEND_MESSAGE_SENDING = 'BACKEND_MESSAGE_SENDING'
export const BACKEND_MESSAGE_SENT = 'BACKEND_MESSAGE_SENT'
export const BACKEND_MESSAGE_FAILED_TO_SEND = 'BACKEND_MESSAGE_FAILED_TO_SEND'

export const BACKEND_SAVE_SETTINGS = 'BACKEND_SAVE_SETTINGS'
export const BACKEND_SETTINGS_SAVED = 'BACKEND_SETTINGS_SAVED'
export const BACKEND_SAVE_SETTINGS_FAILED = 'BACKEND_SAVE_SETTINGS_FAILED'

