export const INITIATE_PURCHASE = 'INITIATE_PURCHASE'
export const PURCHASED = 'PURCHASED'
export const PURCHASE_FAILED = 'PURCHASE_FAILED'

export const INITIATE_CREATE_USER = 'INITIATE_CREATE_USER'
export const USER_CREATED = 'USER_CREATED'
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED'

export const INITIATE_CREATE_REFERRAL_CODE = 'INITIATE_CREATE_REFERRAL_CODE'
export const REFERRAL_CODE_CREATED = 'REFERRAL_CODE_CREATED'
export const CREATE_REFERRAL_CODE_FAILED = 'CREATE_REFERRAL_CODE_FAILED'

